### ISSUE TITLE
How did you connect laser to the NodeMCU?

### ISSUE THREAD

**Issue by AnandVetcha** [surak/arduino#1]
Can you please share a picture displaying how you have connected laser to NodeMCU?

**Comment by surak** [comment]
I haven't. I connected it to an arduino UNO. To be honest, the whole nodemcu pinout is a mystery to me. I posted a question on stackexchange about that: http://arduino.stackexchange.com/questions/33460/following-on-esp8266-board-pins-how-do-they-map-on-the-motor-shield

**Comment by AnandVetcha** [comment]
![image](https://cloud.githubusercontent.com/assets/8841994/22074731/666c09fc-ddcf-11e6-8779-f06a9f6dcc9c.png)



After using my multi meter i tried to understand the pin connection of the Motor shield. Following are my observation's:
GPIO Section:
- All pins corresponding to G row are conencted to ground
- All Pins corresponding to  V row are connected to NodeMCU's 3V3  pin
- D row pins tagged from 0 to 8 correspond to NodeMCU's D1-D8 pins.
- D row pins tagged with SD2, SD3 corresponds to NodeMCU's SD2 , SD3 pin

UTART/SPI section:
- Tags corresponding to the pins are self explanatory

Near the white colored power switch we have a pin called "AD". I couldn't figure how  this motor shield's "AD" pin is interfaced to NodeMCU. Do you have any idea?

Do you have any plans to port your Arduino script to NodeMCU?

**Comment by surak** [comment]
Wow, thank you! NO ONE answered on the two different stack exchanges (electronics and arduino). The script itself runs on nodemcu, see the car-blynk directory here. 
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>

**Comment by AnandVetcha** [comment]
While interfacing the laser module did you power it with 3.3V or 5V? Do we need to place any resistor in series?

**Comment by surak** [comment]
I used 5v, no resistor: https://surak.wordpress.com/2017/01/07/running-a-5v-5mw-650nm-laser-from-arduino/
